"""remove PIN from users

Revision ID: 17077970770e
Revises: c7a43b0b85b7
Create Date: 2026-03-27 11:48:25.460998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17077970770e'
down_revision = 'c7a43b0b85b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.VARCHAR(length=6), nullable=False))

    # ### end Alembic commands ###
