"""PlayerTask table

Revision ID: 3e382cfcbb6d
Revises: c7a43b0b85b7
Create Date: 2024-07-11 00:10:04.448529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e382cfcbb6d'
down_revision = 'c7a43b0b85b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('prerequesite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['prerequesite_id'], ['player_task.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_task_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_task_player_id'))

    op.drop_table('player_task')
    # ### end Alembic commands ###
