"""game table

Revision ID: 8783befbaedb
Revises: a653393ecbda
Create Date: 2024-07-07 15:19:52.566907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8783befbaedb'
down_revision = 'a653393ecbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('time_started', sa.Integer(), nullable=False),
    sa.Column('time_finished', sa.Integer(), nullable=False),
    sa.Column('imposter_count', sa.Integer(), nullable=False),
    sa.Column('reveal_role', sa.Boolean(), nullable=False),
    sa.Column('emergency_meetings', sa.Integer(), nullable=False),
    sa.Column('discussion_time', sa.Integer(), nullable=False),
    sa.Column('emergency_cooldown', sa.Integer(), nullable=False),
    sa.Column('kill_cooldown', sa.Integer(), nullable=False),
    sa.Column('short_tasks', sa.Integer(), nullable=False),
    sa.Column('long_tasks', sa.Integer(), nullable=False),
    sa.Column('common_tasks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    op.drop_table('game')
    # ### end Alembic commands ###
